### ISSUE TITLE
r8188eu driver very slow (not urgent)

### ISSUE THREAD

**Issue by Piqlet** [endeavouros-team/EndeavourOS-ISO#8]
Sorry for the offence, but this also slows down or prevents the installation very much. Kernel 5.15 / 5.16 + TP-Link TL-WN722N v2/v3 [Realtek RTL8188EUS] is very slow and buggy. It drops from 40 Mbps to 1-2 Mbps. [https://linux-hardware.org/?probe=d484e899ef](https://linux-hardware.org/?probe=d484e899ef)

5.10 / 5.13 (Manjaro live iso test) kernel is fine.
```
$ inxi -SNxxx
System:
  Host: eco Kernel: 5.10.90-1-lts x86_64 bits: 64 compiler: gcc v: 11.1.0
    Desktop: KDE Plasma 5.23.5 tk: Qt 5.15.2 wm: kwin_x11 vt: 7
    dm: LightDM 1.30.0 Distro: EndeavourOS base: Arch Linux
Network:
  Device-1: Intel Ethernet I219-V vendor: Micro-Star MSI driver: e1000e
    v: kernel port: N/A bus-ID: 00:1f.6 chip-ID: 8086:15b8 class-ID: 0200
  Device-2: TP-Link TL-WN722N v2/v3 [Realtek RTL8188EUS] type: USB
    driver: r8188eu bus-ID: 1-10:3 chip-ID: 2357:010c class-ID: 0000
    serial: [delete]
```

Related Information :

[https://lore.kernel.org/all/CABtXzjTvsN8sCQq0tMG+VZ8Vu04a1zR20P-hbQf-Mnpmu2gTNg@mail.gmail.com/](https://lore.kernel.org/all/CABtXzjTvsN8sCQq0tMG+VZ8Vu04a1zR20P-hbQf-Mnpmu2gTNg@mail.gmail.com/)

[https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.15-Staging](https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.15-Staging)

**Comment by killajoe** [comment]
r8188eu  is from the kernel itself we do not maintain or install extra drivers for this device.

**Comment by Piqlet** [comment]
_r8188eu is from the kernel itself we do not maintain or install extra drivers for this device._

Yes, that's right, I also say that the default, native, factory driver is the culprit.
Currently, if I want a quick install, I install offline and some way to the older kernel ... like sudo downgrade.

In the meantime I looked at the forum : [https://forum.endeavouros.com/t/wi-fi-often-randomly-crashes-or-just-slows-down/21484](https://forum.endeavouros.com/t/wi-fi-often-randomly-crashes-or-just-slows-down/21484) (second half, towards the end)

What is the easiest solution, I don't know yet.

If you don't want to deal with this, feel free to close it.

**Comment by killajoe** [comment]
> If you don't want to deal with this, feel free to close it.

It is not that I do not want to deal with it, but I do not see any workable solution, using the mentioned aircrack driver is not an option for the ISO (Realtek RTL8188EUS and RTL8188ETV Wi-Fi driver with monitor mode & frame injection support)  also I see a comment that this is the only working driver for TP-Link TL-WN722N v2/v3 [Realtek RTL8188EUS] .
The issue you have could simple be solved with one of the next kernel updates. You could check with one of the last devel ISO  on how it behaves on livesession with it?
https://github.com/endeavouros-team/ISO/releases/tag/0-EndeavourOS-development-ISO-releases

**Comment by Piqlet** [comment]
I agree, it's easiest to wait for the "factory" (what's the official name ?) kernel patch. Only I was new to this situation. For me it's fine to install offline and switch desktop environments.

I tried endeavouros-devel-2022.01.16-x86_64.iso.
The speed test, not bad (10-13 Mbps), but it falls short of a well working wifi (40 Mbps) and the "nmcli dev wifi" is still missing.
[https://www.speedtest.net/result/12662655914.png](https://www.speedtest.net/result/12662655914.png)
[https://www.speedtest.net/result/12662717730.png](https://www.speedtest.net/result/12662717730.png)

![Screenshot_2022-01-25_16-43-49 wifi del 256](https://user-images.githubusercontent.com/16097403/151032145-a3f7c498-e96f-42d6-95cf-2eace9cb7d4d.png)


Another idea is to release the same iso with two different kernels. In the current situation, for example, it would be nice to have an iso with kernel release 5.10, because it works fine with the old one. ( This is interesting because there are so many, 200+ kernels to choose from with the downgrade command for the installed system. While the installation disk has only 1 kernel. )

**Comment by killajoe** [comment]
adding a second kernel is not an option,  ISO size would increase over our limit.
But indeed an LTS ISO would be possible. 
But will need to maintain and develop it first, as it needs a complete review of the build and ins install process, also latest changes on calamares respect now all kernels, before it was needs to set the exact kernel to be used in different places. 
But the ISO build files need some changes and testing to get it working.

**Comment by killajoe** [comment]
I do actually like the idea of an LTS ISO.

**Comment by Piqlet** [comment]
Testing dkms : 
Device : TP-Link TL-WN722N v2/v3 [Realtek RTL8188EUS]

8188eu-dkms : bad
8188eu-aircrack-dkms-git : good
8188eu-dkms-git : good

Results : 

8188eu-dkms : bad
(It is also bad with 5.10 kernel because there is no internet connection.)
```
$ paru -S 8188eu-dkms
:: Resolving dependencies...
:: There are 3 providers available for 8188eu-dkms:
:: Repository AUR:
    1) 8188eu-dkms  2) 8188eu-aircrack-dkms-git  3) 8188eu-dkms-git  
Enter a number (default=1): 1
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (1) 8188eu-dkms-v4.3.0.8_13968-16

...

(1/2) Arming ConditionNeedsUpdate...
(2/2) Install DKMS modules
==> dkms install --no-depmod 8188eu/v4.3.0.8_13968 -k 5.16.15-arch1-1
Error! Bad return status for module build on kernel: 5.16.15-arch1-1 (x86_64)
Consult /var/lib/dkms/8188eu/v4.3.0.8_13968/build/make.log for more information.
==> WARNING: `dkms install --no-depmod 8188eu/v4.3.0.8_13968 -k 5.16.15-arch1-1' exited 10
==> dkms install --no-depmod 8188eu/v4.3.0.8_13968 -k 5.15.30-1-lts
Error! Bad return status for module build on kernel: 5.15.30-1-lts (x86_64)
Consult /var/lib/dkms/8188eu/v4.3.0.8_13968/build/make.log for more information.
==> WARNING: `dkms install --no-depmod 8188eu/v4.3.0.8_13968 -k 5.15.30-1-lts' exited 10
==> dkms install --no-depmod 8188eu/v4.3.0.8_13968 -k 5.10.107-1-lts510
==> depmod 5.10.107-1-lts510
```

8188eu-aircrack-dkms-git : good

```
$ paru -S 8188eu-dkms
:: Resolving dependencies...
:: There are 3 providers available for 8188eu-dkms:
:: Repository AUR:
    1) 8188eu-dkms  2) 8188eu-aircrack-dkms-git  3) 8188eu-dkms-git  
Enter a number (default=1): 2
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (1) 8188eu-aircrack-dkms-git-5.3.9.r145.6146193-1

...

(1/2) Arming ConditionNeedsUpdate...
(2/2) Install DKMS modules
==> dkms install --no-depmod 8188eu/5.3.9.r161.0958f29 -k 5.10.107-1-lts510
Deprecated feature: REMAKE_INITRD
==> dkms install --no-depmod 8188eu/5.3.9.r161.0958f29 -k 5.15.30-1-lts
Deprecated feature: REMAKE_INITRD
==> dkms install --no-depmod 8188eu/5.3.9.r161.0958f29 -k 5.16.15-arch1-1
Deprecated feature: REMAKE_INITRD
==> depmod 5.10.107-1-lts510
==> depmod 5.15.30-1-lts
==> depmod 5.16.15-arch1-1
```

8188eu-dkms-git : good

```
$ paru -S 8188eu-dkms
:: Resolving dependencies...
:: There are 3 providers available for 8188eu-dkms:
:: Repository AUR:
    1) 8188eu-dkms  2) 8188eu-aircrack-dkms-git  3) 8188eu-dkms-git  
Enter a number (default=1): 3
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (1) 8188eu-dkms-git-5.2.2.4.r794.53ed527-1

...

(1/2) Arming ConditionNeedsUpdate...
(2/2) Install DKMS modules
==> dkms install --no-depmod 8188eu/5.2.2.4.r801.bf23ec4 -k 5.16.15-arch1-1
==> dkms install --no-depmod 8188eu/5.2.2.4.r801.bf23ec4 -k 5.15.30-1-lts
==> dkms install --no-depmod 8188eu/5.2.2.4.r801.bf23ec4 -k 5.10.107-1-lts510
==> depmod 5.10.107-1-lts510
==> depmod 5.15.30-1-lts
==> depmod 5.16.15-arch1-1
```

**Comment by killajoe** [comment]
please reopen if someone still have issue with this device.

**Comment by Piqlet** [comment]
I tried the modprobe command.
[https://blog.ostermiller.org/resetting-wireless-networking-on-ubuntu-without-rebooting/](https://blog.ostermiller.org/resetting-wireless-networking-on-ubuntu-without-rebooting/) 
The speed measurement shows maximum (not tried for installation).
In my case, these are the ones to enter. 
```
sudo modprobe -r r8188eu
sudo modprobe -b 8188eu
```

![Screenshot_2022-11-17_15-55-54_8188eu_256](https://user-images.githubusercontent.com/16097403/202513430-379ef98c-0745-4c13-8984-dbfc71ceb44f.png)

(This did not help or was not precise enough. [https://forum.endeavouros.com/t/tp-link-tl-wn722n-is-not-detected-as-wifi-adapter/29264/9](https://forum.endeavouros.com/t/tp-link-tl-wn722n-is-not-detected-as-wifi-adapter/29264/9) )
